In [1]:
import numpy as np
print(np.version.version)

1.26.4


In [2]:
data = np.arange(4, 10)
print(data)

[4 5 6 7 8 9]


In [3]:
# print a boolean 3x3 array with all values = True
# way 1
data1 = np.ones((3, 3)) > 0
print(f'{data1} \n--------------------')

# way 2
data2 = np.ones((3, 3), dtype=bool)
print(f'{data2} \n--------------------')

# way 3
data3 = np.full((3, 3), True, dtype=bool)
print(f'{data3} \n--------------------')

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 
--------------------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 
--------------------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 
--------------------


In [5]:
# get the array with pre condition
data = np.arange(0, 10)
print(data)

# find odd number
data_odd = data[data % 2 == 1]
print(data_odd)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [7]:
# replace the elements with other values
data[data % 2 == 1] = -1
print(data)

# another way
out = np.where(data % 2 == 1, -1, data)
print(out)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
# convert an 1D array to 2D array
data = np.arange(10)
print(data)

#
data_2d = data.reshape(2, 5)
print(data_2d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
# way_1
data_1 = np.arange(10).reshape(2, -1)
data_2 = np.repeat(7, 10).reshape(2, -1)

out1 = np.concatenate([data_1, data_2], axis = 0)
print(out1)

out2 = np.vstack([data_1, data_2])
print(out2)

out3 = np.r_[data_1, data_2]
print(out3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [17]:
# get the common values of 2 arrays
data1 = np.array([1, 2, 3, 2])
data2 = np.array([7, 2, 1, 8])

out = np.intersect1d(data1, data2)
print(out)
print(np.setdiff1d(data1, data2))

[1 2]
[3]


In [18]:
# get the index where the values of 2 array matched
data1 = np.array([1, 2, 3, 4, 5, 6])
data2 = np.array([1, 1, 1, 6, 6, 6])

comp = data1 == data2
indices = comp.nonzero()
print(indices)

(array([0, 5], dtype=int64),)


In [23]:
# get all the value in a range
data = np.array([1, 8, 3, 9, 7, 6])
print(data)

indices = np.nonzero(data >= 7) # or np.where(data >= 7)
out1 = data[indices] 
print(out1)

out2 = data[data >= 7]
print(out2)

[1 8 3 9 7 6]
[8 9 7]
[8 9 7]


In [2]:
import numpy as np
# use a user-defined function for ndarray using np.vectorize()
def get_max(x, y):
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(get_max, otypes = [int])

data_1 = np.array([5, 3, 8, 2, 7])
data_2 = np.array([2, 7, 3, 1, 8])
out1 = pair_max(data_1, data_2)
print(out1)

[5 7 8 2 8]


In [3]:
import numpy as np

data = np.arange(9).reshape(3, 3)
print(data, '\n')

out = data[:, [1, 0, 2]]
print(out)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [4]:
data = np.arange(9).reshape(3, 3)
print(data, '\n')

out  = data[[1, 0, 2], :]
print(out)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [5]:
import numpy as np

data = np.arange(9).reshape(3, 3)
print(data, '\n')

out = data[::-1, :]
print(out)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [7]:
# reverse element in each array
out2 = data[:, ::-1]
print(out2)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [10]:
# create an 2d array with random numbers
import numpy as np

data1 = np.random.uniform(5, 10, size=(2, 3))
print(data1, '\n')

data2 = np.random.random([2, 3])

[[7.54489396 5.00709277 7.68964071]
 [6.735317   5.31336695 6.21331082]] 



# Vector Calculations

In [11]:
u = np.array([1, 2, 4, 2])
print(np.linalg.norm(u))

5.0
