# Vector Calculations

In [1]:
import numpy as np

In [2]:
u = np.array([1, 2, 4, 2])
print(np.linalg.norm(u))

5.0


In [4]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

print(x + y)
print(x - y)

[ 6  8 10 12]
[-4 -4 -4 -4]


In [5]:
# hadamard multiplication and division
print(x * y)
print(x / y)

[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [6]:
# dot product
v = np.array([1, 2])
w = np.array([2, 3])

print(v.dot(w))
print(np.dot(v, w))

8
8


In [8]:
X = np.array([[1, 2], [3, 4]])
print(np.transpose(X))
print(X.T)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
